name: .NET and Angular CI/CD

on: [push]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore blog-backend
    
    - name: Build
      run: dotnet build blog-backend --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish blog-backend --configuration Release --output ./publish --no-restore
      
  build-angular:
    runs-on: ubuntu-latest
    needs: build-dotnet

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.2'
    
    - name: Install dependencies
      run: npm install --prefix blog-frontend
      
    - name: Build
      run: npm run build --prefix blog-frontend -- --prod

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: angular-artifacts
        path: blog-frontend/dist/
